version: "3.5"
services:
  backend_application:
    env_file:
      - .env
    build: .
    image: code_init_test_image:latest
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    deploy:
      update_config:
        parallelism: 1
        max_failure_ratio: 0
        delay: 3s
        failure_action: rollback
      restart_policy:
        max_attempts: 3
        condition: on-failure
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
    volumes:
      - .:/src
